# https://hub.docker.com/r/qxip/docker-janus

version: '2'

services:      
  janus:
    container_name: janus
    image: qxip/docker-janus
    ports:
      - "7889:7889"
      - "7089:7089"
      - "8089:8089"
      - "7088:7088"
      - "8088:8088"
      - "8000:8000"
      - "8080:8080"
      - "10000-10200:10000-10200/udp"
