FROM canyan/janus-gateway:0.10.7

# Use custom configuration
COPY janus.jcfg /usr/local/etc/janus/janus.jcfg
COPY janus.transport.http.jcfg /usr/local/etc/janus/janus.transport.http.jcfg
COPY janus.plugin.videoroom.jcfg /usr/local/etc/janus/janus.plugin.videoroom.jcfg
