# https://github.com/canyanio/janus-gateway-docker

version: '2.1'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    build: '.'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    # volumes:
      # - "./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      # - "./etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
    restart: always
